"use client";

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

/*
export const metadata: Metadata = {
  title: "X (Twitter)",
  description: "Generated by create next app",
};
*/

const queryClient = new QueryClient();

/*
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
*/

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <title>X (Twitter)</title>
      </head>
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <GoogleOAuthProvider clientId="738530219049-t9rq903hpl1ecs2cv6ld6cg7mvv3o3on.apps.googleusercontent.com">
            {children}
            <Toaster />
            <ReactQueryDevtools />
          </GoogleOAuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
